# Generated by Django 5.2 on 2025-04-07 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ülesanne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pealkiri', models.CharField(max_length=200)),
                ('kirjeldus', models.TextField()),
                ('pilt', models.ImageField(blank=True, null=True, upload_to='ülesanded/')),
                ('loodud', models.DateTimeField(auto_now_add=True)),
                ('kasutaja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AlamÜlesanne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sisu', models.CharField(max_length=300)),
                ('tehtud', models.BooleanField(default=False)),
                ('ülesanne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alamülesanded', to='jagaja.ülesanne')),
            ],
        ),
    ]
