# Generated by Django 5.2 on 2025-04-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jagaja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ülesanne',
            name='tähtaeg',
            field=models.DateField(blank=True, null=True),
        ),
    ]
